### ISSUE TITLE
How to Traverse through trees ?

### ISSUE THREAD

**Issue by aftabnaveed** [nicmart/Tree#12]
Hey thankyou for this nice tree implementation, do you know how can Iterate through the root and its all children nodes?

**Comment by aftabnaveed** [comment]
ok I just figured it out with this little recursive function 

```php
function get_blocks($block) {

	if($block->isLeaf()) {
		return $block;
	}

	$children = $block->getChildren();

	foreach($children as $block) {
		echo $block->getValue();
		echo "\n";
	 	get_blocks($block);
	}	
}	
```

**Comment by localheinz** [comment]
@aftabnaveed 

Maybe you will like this: #24?
