### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by pcwhizkid** [nicmart/Tree#13]
I want to use [Sourcegraph](https://sourcegraph.com) for Tree code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/nicmart/Tree. (It should only take 30 seconds.)

Thank you!

**Comment by nicmart** [comment]
Done, but please note that Sourcegraph does not support PHP for now...
