### ISSUE TITLE
Use String key to represent a Node

### ISSUE THREAD

**Issue by aftabnaveed** [nicmart/Tree#14]
I see at the moment children member variable is private and it uses the default integer as array index, I wanted to change that behaviour to support string keys in addChild so I overrode that method in my child class, but since children is private to NodeTrait I can't override the children behaviour. My question is, is there any particular reason for keeping the children private in NodeTrait?

**Comment by nicmart** [comment]
The more is private the better :)

You can override the addChild method using the trait in an other class, without extending the default one:

```php
class NodeWithNamedChildren implements NodeInterface
{
    use NodeTrait;

    public function addChild(NodeInterface $child, $name = null)
    {
        $child->setParent($this);
        
        if (isset($name)) {
            $this->children[$name] = $child;
        } else {
            $this->children[] = $child;
        }

        return $this;
    }
}
```
