### ISSUE TITLE
Iterable Node and Proxy Node

### ISSUE THREAD

**Issue by benglass** [nicmart/Tree#16]
Great library. I just wrote a few traits for a project we are using it if you are interested in including them I can make a PR.

IterableNode just implements IteratorAggregate to allow for foreaching over a node/tree

```
trait IterableNodeTrait 
{
    public function getIterator() {
        return new ArrayIterator($this->getChildren());
    }
}
```

ProxyNodeTrait proxies method calls on the Node to the underlying value object so you can do $node->getName() instead of $node->getValue()->getName(). In our use case the combination of these makes our template code less aware that its dealing with a tree structure since it acts like an array of business objects (for example a tree of clients with their files).

```
trait ProxyNodeTrait 
{

    /**
     * Proxy method calls to the value of the node
     * This makes it so you can do $node->getName() instead of $node->getValue()->getName()
     * 
     * @param string $name Method name to call
     * @param array $arguments Arguments for the method
     */
    public function __call($name, array $arguments) {
        $value = $this->getValue();
        $method = $this->determineMethodName($name);

        if ($method) {
            return call_user_func_array([$value, $method], $arguments);
        }

        throw new BadMethodCallException('Invalid method call on '.get_class($this->getValue()).': '.$name);
    }

    /**
     * Determine which method to call on the node's value object based on the $name passed to __call
     * Looks for $name() and get$name()
     * 
     * @param string $name Method name
     * @return string|false
     */
    private function determineMethodName($name) {
        $object = $this->getValue();
        $methods = [$name, 'get'.ucfirst($name)];
        foreach ($methods as $method) {
            if (is_callable([$object, $method])) {
                return $method;
            }
        }
        return false;
    }
}
```

**Comment by nicmart** [comment]
In general I don't like traits very much, so I try to use them as less as possible in my libraries.
Traits in PHP are just copy and paste at the language level, and nothing more. This makes very difficult to guess what they will do without looking who is using them. So I prefer to not use them as long as there is not a very strong use case.
