### ISSUE TITLE
PHP Warning: Undefined array key -1

### ISSUE THREAD

**Issue by pedzed** [nicmart/Tree#208]
#### Steps required to reproduce the problem

```php
use Tree\Builder\NodeBuilder;

(new NodeBuilder)->value('some value')->end()->getNode();
```

#### Expected Result

An exception should to be thrown if pre-conditions are not met.

#### Actual Result

```
PHP Warning:  Undefined array key -1 in vendor/nicmart/tree/src/Builder/NodeBuilder.php on line 43
```

---

Code in question:

https://github.com/nicmart/Tree/blob/409ba5d49811f5ff68a8c276cfec325d2bda4d01/src/Builder/NodeBuilder.php#L41-L44

**Comment by localheinz** [comment]
Thank you for reporting, @pedzed!
