### ISSUE TITLE
fill tree with node contains parent

### ISSUE THREAD

**Issue by Viky-zhang** [nicmart/Tree#31]
can I fill the tree with data with parent like:
```php
$data = array(
    // 0 is root
    array('id' => 1, 'parent' => 0, 'name' => 'Europe'),
    array('id' => 4, 'parent' => 0, 'name' => 'Asia'),
    // --
    array('id' => 7, 'parent' => 1, 'name' => 'Germany'),
    array('id' => 8, 'parent' => 1, 'name' => 'Germany2'),
    array('id' => 10, 'parent' => 4, 'name' => 'Portugal'),
);
```

```php
     root
      / \
    1    4
   /  \   \
 7     8   10
```

**Comment by nicmart** [comment]
Hi, I don't fully understand your question, which is the issue?

**Comment by Viky-zhang** [comment]
using the `$data` above, and new a root node like:
```php
$nodeRoot = new Node($data);
```

then `$nodeRoot` contains children `1` and `4`
and `1` contains `7` and `8` 
and `4` contains `10`

that is because my source data is like the `$data`.

**Comment by nicmart** [comment]
I still don't understand which is the question or the expected result.
Are you asking how to instantiate a tree that is reflecting that structure?

With `new Node($data)` you are just creating a node whose value is $data.

**Comment by Viky-zhang** [comment]
yeah , `Are you asking how to instantiate a tree that is reflecting that structure?` is my question.

Can this lib add support for such feature?

**Comment by nicmart** [comment]
Of course, you just have to create the tree with the proper values.
The README explains everything about that.

**Comment by Viky-zhang** [comment]
I can ` instantiate a tree that is reflecting that structure` by writing many lines of code.
I think `one line support` will be very nice.

**Comment by nicmart** [comment]
Ah now I understand, you would like a factory that is building the tree given your flat array.
I thought you ment that that was impossible to do with the library.
You can use something like

```php
function buildTree(array $data) {
    $root = new Node("root");
    $nodes = array(0 => $root);

    foreach ($data as $nodeData) {
       list($id, $parent, $name) = $nodeData;
       $node = new Node($name);
       $nodes[$id] = $node;
       if (isset($nodes[$parent]) {
           $nodes[$parent]->addChild($node);
       }
    }

    return $root;
}
```

You need to have children defined after the parent in the data array, or you can improve the function sorting the array by parentid first before traversing it.
